"""
Complementing a Strand of DNA

    complement(s::String) -> String

Given: A DNA string `s` of length at most 1000 bp.

Return: The reverse complement `sc` of `s`.

# Arguments
- `s::String`: a DNA string
"""
function complement(s::String)
    pairs = Dict('A' => 'T', 'T' => 'A', 'C' => 'G', 'G' => 'C')
    sc = ""
    for base in reverse(s)
        sc *= pairs[base]
    end
    return sc
end 

println(complement("GAGTCGCTGGGCTCCAGGATTCCAAGAGGTCACAGACCTGTCCTGGCTAGGGGACAAACGTCACGCTTTGGCTCCTAGAACGTACGGCACATGTAGAAATTCCGCCCATGGATTCGAGAGATGCCATCTTTCCACCAAATCCGGAAATAAGCGCCTCCGCCAGGATCTGTACGAAATTAATCATCGGTATAGAGGGGACGTACCCTGGGTTACGATATCACACACTTTGTTAGCCGATCCTCCCCTCCCCAGCGTAAGCTTGCCGGACTCGTTAGCGCACTGATACTATACCTAATAGAGTGTTATAGATGCGCCAAGGTTTAGTTATAGCCCGCGACTGACTGTTCCACCATTCTTGTAACCGGCTGCCCAACATTATATGTCGCGATTATCGCCTTGCTGGTACACGTGTCCGCGGATTGAGTGGAGCCGATGCAGGTTTTCAATCGTAGGTTGATTACGATTTGTGTGGGTGTTTGCTGTATTTTTGCAACAAGTTCAACCAGTCGCCATGAACCACCGTATCAGGACGCGTGCCCGTCTTGTCTTTCGACATATCGCGGTTGAGCACTCGCGGCCGAAAGGAGTCTCGTATTGTAAAACTGGTGAGCACTCCGTTGACGCCAACTCGGTTTCGGTCCTGACCGGCCACATTGATTCACGAGAGGGTATGCGCTCTCTGCAAGGGCACTTCTTGATGCGGGAGGAATGTGTATGTAATCAGGGGATGCCCCCAGGCGACCTGTTGTCGGGAGACTATTTGTCATGTGCTTGGTTCCTGCCTAGGGTCAGATAAAACCGGCCCAACTGAGAGTGATTGTCCCGGCTAAACAAATAGCAGTACACGTCTTATTTTTAATTGCAACTTTGACCCGAAATAGTTTCTATCACCAGGTACTTTCCGAGTCCTGCGGAAGTGCATTTCTGGATGCGGTTTTGTTGTTAGAAATAAAAAAGATTGGTGGCCTTGTCCAGAATT"))