""" 
Counting DNA Nucleotides

    countnucleotides(s::string)

Returns a count of each nucleotide in the sequence
in the order A, C, G, T.

# Arguments
- `s::String`: a DNA sequence
"""
function countnucleotides(s::String)
    counts = Dict(base => 0 for base in "ACGT")
    for base in s
        counts[base] += 1
    end
    return counts
end

s = "CGCTCAATTATGTTGAACGATTGATATTAATTCCCTAGGGAGGTAGACGGATTATTTGTTTGTAAGGGTTTATACAATCGGGGCATCACCTAGCGCCGACCTTCATGGTTCATAGGCGGGGACCGGGGTGTCTAGTACTTACAGGGGAAAACGTGATGGGCACGCCCCGGGGAAAACAATGGCAATGAGAGCCTGAAGATACTTCCTCGAGGATGGTTGTCACCACGTGAGTGTCAGTCGCACGTTAAGCAGTTTTTAGACGTCGATGTAACATACCAGCCTAAATCCGGTGATGACTGGCCTCTCTAAGCCGCCCCATCTATCCGGAGGACAGGTCACTTCATCTTTATTGCGCTGGGGCGGGCGAAACAGGAAGTTCACTGTGGCTCATACCTGATCTGTTACCTTTGCGGGGACGACGAAGGGACCACTTGAAACTGTAGCTTGACTCTCGTAATGCGCTTAAAGTCAGGGAAATGAAAGCATGGCGCGGTCCTTCCCCGGCATTGGTGCACGCTTGGTTCCTTACGCTAGTCGCAAGCTGAGATGGTGAACGGAGAGGGCTTGTGCCTGTTATGGCAACCTCCCACCTCACTGGCCAAGGCACGGTTTATGCTATTGACCCCCAGGATGGACTGGTAGTTCCTAACGCGCCACTCGCGCCAGGTGCACCGTGTCAAGTCTCTACATGTGAACGTACTATACCAGGGTTCAACGACAAATCCGGCTGTGTCTACTAATCATTTTACTACGTTGAGGAGCATCAAAGGTTAGTGTTATTCTGCCATTGGGCTGGGCGATGCTCGCCTTTCGCCGCGAGATCGTGATCTCACCCACGGTAGAATTTTCAATGCGATACCGAAAGCCCCCGAAGGGCGCAGC"

counts = countnucleotides(s)
for base in "ACGT"
    print("$(counts[base]) ")
end 