"""
Finding a Motif in DNA

    motifsearch(s::String, t::String) -> Array

Finds the locations of a motif `t` in nucleotide sequence `s`.

# Arguments
- `s::String`: a DNA string.
- `t::String`: a DNA string.

# Returns
- `Array`: all locations of `t` as a substring of `s`.
"""
function motifsearch(s::String, t::String)
    locations = []
    for i in 1:length(s)-length(t)+1
        if s[i:i+length(t)-1] == t
            push!(locations, i)
        end
    end
    return locations
end

s = "ATACACCACACACCACACCACGACCACACGCACCACACTACCACACAACCACACGCCCTACCACACACCACACCCGACCACACCGCATATTAGACCACACGACCACACACCACACTACCACACCCAGAACCACACCTACCACACTACCACACACCACACAACCACACGGACCACACTACATTAACCACACCTCGGACCACACACCACACTACCACACGCACGCCGTCGTCACCACACCGCATCACCACACTACCACACTGGCAACCACACCACCCTACCACACCGACCACACGTACCACACTACGACCACACAACCACACGGACCACACTGACTCTACCACACAACCACACATACCACACTACCACACGACCACACCGCCAACCACACACACTAACCACACACCACACACCACACGAGGAGGCACAAGACCACACCAAGGAGCGAGGACCACACACCACACGAACCACACACCACACAAAACCACACTTTTTACCACACACCACACATTATCACCACACACCACACTGGCGTACCACACAGCACCACACTACCACACGACCACACACCACACGACCACACCGGCTTACATACCACACAGGGACCACACACCACACGTCACCACACATCACCACACGGAACCACACTTCGCTTAGACCACACAACCACACGATGGACCACACTGCTGACCACACCACTACCACACACCACACCACCACACACCACACACCACACTCGCTTACCACACCTAAGGGTTTTGACCACACACCACACGAACCACACCACCACACACCACACACCACACTGGTACCACACTCACCACACACCACACCACACCACACGACCACACCAACACGACCACACACCACACGTACCACACAGACCACACACCACACTGGAAACCACACTACCACACAAAGACCACACCCGACACCACACTCGACCACACACCACACACCACAC"
t = "ACCACACAC"

for i in motifsearch(s, t)
    print(i, " ")
end