"""
Finding a Motif in DNA

    motifsearch(s::String, t::String) -> Int

Finds the locations of a motif `t` in nucleotide sequence `s`.
"""
function motifsearch(s::String, t::String)
    locations = []
    for i in 1:length(s)-length(t)+1
        if s[i:i+length(t)-1] == t
            push!(locations, i)
        end
    end
    return locations
end

s = "ATACACCACACACCACACCACGACCACACGCACCACACTACCACACAACCACACGCCCTACCACACACCACACCCGACCACACCGCATATTAGACCACACGACCACACACCACACTACCACACCCAGAACCACACCTACCACACTACCACACACCACACAACCACACGGACCACACTACATTAACCACACCTCGGACCACACACCACACTACCACACGCACGCCGTCGTCACCACACCGCATCACCACACTACCACACTGGCAACCACACCACCCTACCACACCGACCACACGTACCACACTACGACCACACAACCACACGGACCACACTGACTCTACCACACAACCACACATACCACACTACCACACGACCACACCGCCAACCACACACACTAACCACACACCACACACCACACGAGGAGGCACAAGACCACACCAAGGAGCGAGGACCACACACCACACGAACCACACACCACACAAAACCACACTTTTTACCACACACCACACATTATCACCACACACCACACTGGCGTACCACACAGCACCACACTACCACACGACCACACACCACACGACCACACCGGCTTACATACCACACAGGGACCACACACCACACGTCACCACACATCACCACACGGAACCACACTTCGCTTAGACCACACAACCACACGATGGACCACACTGCTGACCACACCACTACCACACACCACACCACCACACACCACACACCACACTCGCTTACCACACCTAAGGGTTTTGACCACACACCACACGAACCACACCACCACACACCACACACCACACTGGTACCACACTCACCACACACCACACCACACCACACGACCACACCAACACGACCACACACCACACGTACCACACAGACCACACACCACACTGGAAACCACACTACCACACAAAGACCACACCCGACACCACACTCGACCACACACCACACACCACAC"
t = "ACCACACAC"

for i in motifsearch(s, t)
    print(i, " ")
end