""" 
Counting DNA Nucleotides

    countnucleotides(s::string) -> Dict{Char, Int}

Given: A DNA string `s` of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in `s`.

# Arguments
- `s::String`: a DNA sequence.

# Returns
- `Dict{Char, Int}`: a dictionary of base => count.
"""
function countnucleotides(s::String)
    counts = Dict(base => 0 for base in "ACGT")
    for base in s
        counts[base] += 1
    end
    return counts
end

s = "CGCTCAATTATGTTGAACGATTGATATTAATTCCCTAGGGAGGTAGACGGATTATTTGTTTGTAAGGGTTTATACAATCGGGGCATCACCTAGCGCCGACCTTCATGGTTCATAGGCGGGGACCGGGGTGTCTAGTACTTACAGGGGAAAACGTGATGGGCACGCCCCGGGGAAAACAATGGCAATGAGAGCCTGAAGATACTTCCTCGAGGATGGTTGTCACCACGTGAGTGTCAGTCGCACGTTAAGCAGTTTTTAGACGTCGATGTAACATACCAGCCTAAATCCGGTGATGACTGGCCTCTCTAAGCCGCCCCATCTATCCGGAGGACAGGTCACTTCATCTTTATTGCGCTGGGGCGGGCGAAACAGGAAGTTCACTGTGGCTCATACCTGATCTGTTACCTTTGCGGGGACGACGAAGGGACCACTTGAAACTGTAGCTTGACTCTCGTAATGCGCTTAAAGTCAGGGAAATGAAAGCATGGCGCGGTCCTTCCCCGGCATTGGTGCACGCTTGGTTCCTTACGCTAGTCGCAAGCTGAGATGGTGAACGGAGAGGGCTTGTGCCTGTTATGGCAACCTCCCACCTCACTGGCCAAGGCACGGTTTATGCTATTGACCCCCAGGATGGACTGGTAGTTCCTAACGCGCCACTCGCGCCAGGTGCACCGTGTCAAGTCTCTACATGTGAACGTACTATACCAGGGTTCAACGACAAATCCGGCTGTGTCTACTAATCATTTTACTACGTTGAGGAGCATCAAAGGTTAGTGTTATTCTGCCATTGGGCTGGGCGATGCTCGCCTTTCGCCGCGAGATCGTGATCTCACCCACGGTAGAATTTTCAATGCGATACCGAAAGCCCCCGAAGGGCGCAGC"

counts = countnucleotides(s)
for base in "ACGT"
    print("$(counts[base]) ")
end 