"""
Complementing a Strand of DNA

    complement(seq::String)

Returns the reverse complement of a DNA string.

# Args
- seq: a DNA string
"""
function complement(seq::String)
    pairs = Dict('A' => 'T', 'T' => 'A', 'C' => 'G', 'G' => 'C')
    complement = ""
    for base in reverse(seq)
        complement *= pairs[base]
    end
    println(complement)
    return complement
end 

complement("GAGTCGCTGGGCTCCAGGATTCCAAGAGGTCACAGACCTGTCCTGGCTAGGGGACAAACGTCACGCTTTGGCTCCTAGAACGTACGGCACATGTAGAAATTCCGCCCATGGATTCGAGAGATGCCATCTTTCCACCAAATCCGGAAATAAGCGCCTCCGCCAGGATCTGTACGAAATTAATCATCGGTATAGAGGGGACGTACCCTGGGTTACGATATCACACACTTTGTTAGCCGATCCTCCCCTCCCCAGCGTAAGCTTGCCGGACTCGTTAGCGCACTGATACTATACCTAATAGAGTGTTATAGATGCGCCAAGGTTTAGTTATAGCCCGCGACTGACTGTTCCACCATTCTTGTAACCGGCTGCCCAACATTATATGTCGCGATTATCGCCTTGCTGGTACACGTGTCCGCGGATTGAGTGGAGCCGATGCAGGTTTTCAATCGTAGGTTGATTACGATTTGTGTGGGTGTTTGCTGTATTTTTGCAACAAGTTCAACCAGTCGCCATGAACCACCGTATCAGGACGCGTGCCCGTCTTGTCTTTCGACATATCGCGGTTGAGCACTCGCGGCCGAAAGGAGTCTCGTATTGTAAAACTGGTGAGCACTCCGTTGACGCCAACTCGGTTTCGGTCCTGACCGGCCACATTGATTCACGAGAGGGTATGCGCTCTCTGCAAGGGCACTTCTTGATGCGGGAGGAATGTGTATGTAATCAGGGGATGCCCCCAGGCGACCTGTTGTCGGGAGACTATTTGTCATGTGCTTGGTTCCTGCCTAGGGTCAGATAAAACCGGCCCAACTGAGAGTGATTGTCCCGGCTAAACAAATAGCAGTACACGTCTTATTTTTAATTGCAACTTTGACCCGAAATAGTTTCTATCACCAGGTACTTTCCGAGTCCTGCGGAAGTGCATTTCTGGATGCGGTTTTGTTGTTAGAAATAAAAAAGATTGGTGGCCTTGTCCAGAATT")